<?php

namespace Merchant\Logic;

/**
 * Class AdministratorLogic
 * @package Merchant\Logic
 * 商品
 */
class CheapGroupLogic extends BaseLogic {

    /**
     * @param array $request
     * @return mixed
     */
    function getList($request = array()) {
        $param['where']['status'] = array("lt",9);
        $param['where']['merchant_id'] = getMerchantId();
        $param['page_size'] = C('LIST_ROWS'); //页码
        $param['parameter'] = $request; //拼接参数
        $result = D('CheapGroup')->getList($param);
//        dump(D('CheapGroup')->getLastSql());
//        dump($result);
        foreach($result['list'] as $k=>$v){
            $count = M('GroupGoods')->where("cheap_group_id={$v['id']}")->count();
            $result['list'][$k]['num'] = $count ? $count : '0';
        }
        return $result;
    }

    /**
     * @param $request
     * @return mixed
     */
    function findRow($request = array()) {

        if(!empty($request['id'])) {
            $param['where']['admin.id'] = $request['id'];
        } else {
            $this->setLogicError('参数错误！'); return false;
        }
        $param['where']['merchant_id'] = getMerchantId();
        $param['where']['status'] = array("lt",9);
        $row = D('CheapGroup')->findRow($param);
        if(!$row) {
            $this->setLogicError('未查到此记录！'); return false;
        }
        $count = M('GroupGoods')->where("cheap_group_id={$row['id']}")->count();
        $total_price = M('GroupGoods')->alias('c')->field('shop_price')->join(C('DB_PREFIX').'goods g ON g.id=c.goods_id')->where("cheap_group_id={$row['id']}")->sum('shop_price');
        $row['num'] = $count ? $count : '0';
        $row['total_price'] = $total_price ? $total_price : '0.00';
        return $row;
    }

    function faceIndex($request = array()){

        $param['where']['goods.merchant_id'] = getMerchantId();//店铺筛选
        $param['where']['goods.status'] = array('lt',9);//状态
        $param['order'] = 'create_time DESC';//排序
        $param['page_size'] = C('LIST_ROWS'); //页码
        $param['parameter'] = $request; //拼接参数
        $result = D('CheapGroupFace')->getList($param);

        return $result;
    }

    function processData($data = array())
    {
        $data['update'] = time();
        $data['start_time'] = strtotime($data['start_time']);
        $data['end_time'] = strtotime($data['end_time']);
        return parent::processData($data); // TODO: Change the autogenerated stub
    }


}